<? $this->headTitle('Список Авто'); ?>
<? $this->headTitle('Список Моделей'); ?>

<div class="divlink">
    <a href="<?=$this->url('models', ['mfaId' => $mfaId]);?>" style="float: right;">Назад</a>
    <H2>Список Автомобилей</H2>
    <? if (count($arrFuel) > 0): ?>
        <table border='1' frame='box' rules='all'>
            <tr>
                <td>
                    <a href="<?=$this->url('cars', ['mfaId' => $mfaId, 'modId' => $modId]); ?>">Все</a>
                </td>
                <? foreach ($arrFuel as $fuel): ?>
                    <? /* @var $fuel \Tecdoc\Entity\TypesFuel */ ?>
                    <td>
                        <a href="<?=$this->url('cars', ['mfaId' => $mfaId, 'modId' => $modId, 'fuelId' => $fuel->getDesId()]); ?>"><?=$fuel->getDesText(); ?></a>
                    </td>
                <? endforeach; ?>
            </tr>
        </table>
    <? endif; ?>
    <table border='1' frame='box' rules='all' style="font-size: 13px;">
        <tr>
            <th>Тип</th>
            <th>Описание</th>
            <th>С</th>
            <th>По</th>
            <th>Мощн. (кВ)</th>
            <th>Мощн. (ЛС)</th>
            <th>Объем куб.см.</th>
            <th>Вид конструкции</th>
            <th>Тип топлива</th>
            <th></th>
        </tr>
        <? foreach ($cars as $car): ?>
            <? /* @var $car \Tecdoc\Entity\Types */ ?>
            <tr>
                <td><?=$car->getCds(); ?></td>
                <td><a href='#'><?=$car->getMmtCds(); ?></a></td>
                <td><?=$car->getPconStart(); ?></td>
                <td><?=$car->getPconEnd(); ?></td>
                <td><?=$car->getKwFrom(); ?></td>
                <td><?=$car->getHpFrom() ?></td>
                <td><?=$car->getCcm(); ?></td>
                <td><?=$car->getBodyDes(); ?></td>
                <td><?=$car->getFuelDes(); ?></td>
                <td><a href='<?=$this->url('fullInfo', ['typId' => $car->getTypId()]); ?>'>Полная информация</a></td>
            </tr>
        <? endforeach; ?>
    </table>
    <br/>
</div>
