<? $this->headTitle('Каталог'); ?>
<? if ($manuf && count($manuf) > 0): ?>
    <nav class="catalog-brend-menu">
        <ul>
            <? foreach ($manuf as $val): ?>
                <? /* @var $val \Tecdoc\Entity\Manufacturers */
                $image = '/img/manuf/256/placeholder.png';
                if (file_exists('./public/img/manuf/256/' . $val->getMfaId() . '.png'))
                    $image = '/img/manuf/256/' . $val->getMfaId() . '.png'; ?>
                <li><a href="#"><div><?=$val->getMfaBrand(); ?></div><img src="<?=$image; ?>" alt=""></a></li>
            <? endforeach; ?>
        </ul>
    </nav>
<? endif; ?>