<? $this->headTitle('Информация по  Авто'); ?>
<? /* @var $fullInfo \Tecdoc\Entity\TypesFullInfo */ ?>

<div class="divlink">
    <a href="<?=$this->url('cars', ['modId' => $fullInfo->getModId()]);?>" style="float: right;">Назад</a>
    <H2>Полная информация по автомобилю</H2>
    <table border='1' frame='box' rules='all'>
        <tr>
            <td colspan='2' align='center' bgcolor='#5588ee'><span style='color:white;'>Общий</span></td>
        </tr>
        <tr>
            <td align='center'>Тип</td>
            <td align='center'><?=$fullInfo->getCds(); ?></td>
        </tr>
        <tr>
            <td align='center'>Описание</td>
            <td align='center'><?=$fullInfo->getMmtCds(); ?></td>
        </tr>
        <tr>
            <td align='center'>Год выпуска (С - По)</td>
            <td align='center'>
                <?=$fullInfo->getPconStart() . " - " . $fullInfo->getPconEnd(); ?>
            </td>
        </tr>
        <tr>
            <td colspan='2' align='center' bgcolor='#5588ee'><span style='color:white;'>Конструкция</span></td>
        </tr>
        <tr>
            <td align='center'>Вид конструкции</td>
            <td align='center'><?=$fullInfo->getKvBodyDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Вид привода</td>
            <td align='center'><?=$fullInfo->getKvDriveDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Вид сборки</td>
            <td align='center'><?=$fullInfo->getKvModelDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Двери</td>
            <td align='center'><?=$fullInfo->getDoors(); ?></td>
        </tr>
        <tr>
            <td align='center'>Бак</td>
            <td align='center'><?=$fullInfo->getTank(); ?></td>
        </tr>
        <tr>
            <td colspan='2' align='center' bgcolor='#5588ee'><span style='color:white;'>Техническая информация</span></td>
        </tr>
        <tr>
            <td align='center'>Мощн. (кВ)</td>
            <td align='center'><?=$fullInfo->getKwFrom(); ?></td>
        </tr>
        <tr>
            <td align='center'>Мощн. (ЛС)</td>
            <td align='center'><?=$fullInfo->getHpFrom(); ?></td>
        </tr>
        <tr>
            <td align='center'>Объем куб.см.</td>
            <td align='center'><?=$fullInfo->getCcm(); ?></td>
        </tr>
        <tr>
            <td align='center'>Конфигурация оси</td>
            <td align='center'><?=$fullInfo->getKvAxleDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Тоннаж</td>
            <td align='center'><?=$fullInfo->getMaxWeight(); ?></td>
        </tr>
        <tr>
            <td align='center'>Объем двигателя в литрах</td>
            <td align='center'><?=$fullInfo->getLitres(); ?></td>
        </tr>
        <tr>
            <td align='center'>Цилиндр</td>
            <td align='center'><?=$fullInfo->getCylinders(); ?></td>
        </tr>
        <tr>
            <td align='center'>Напряжение</td>
            <td align='center'><?=$fullInfo->getKvVoltageDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>ABS</td>
            <td align='center'><?=$fullInfo->getKvAbsDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>ASR</td>
            <td align='center'><?=$fullInfo->getKvAsrDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Вид двигателя</td>
            <td align='center'><?=$fullInfo->getKvEngineDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Вид тормозов</td>
            <td align='center'><?=$fullInfo->getKvBrakeTypeDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Тормозная система</td>
            <td align='center'><?=$fullInfo->getKvBrakeSystDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Вид горючего</td>
            <td align='center'><?=$fullInfo->getKvFuelDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Вид катализатора</td>
            <td align='center'><?=$fullInfo->getKvCatalystDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Привод каробка-передач</td>
            <td align='center'><?=$fullInfo->getKvTransDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Заправка горючего</td>
            <td align='center'><?=$fullInfo->getKvFuelSupplyDes(); ?></td>
        </tr>
        <tr>
            <td align='center'>Количество клапанов на одну камеру сгорания</td>
            <td align='center'><?=$fullInfo->getValves(); ?></td>
        </tr>
        <tr>
            <td colspan='2' align='center' bgcolor='#5588ee'><span style='color:white;'>Двигатель</span></td>
        </tr>
        <tr>
            <td align='center' bgcolor='#5588ee'>Двигатель (Описание)</td>
            <td align='center' bgcolor='#5588ee'>Год выпуска (С - По)</td>
        </tr>
        <? if ($engines != null && count($engines) > 0)
            foreach ($engines as $engine): ?>
            <? /* @var $engine \Tecdoc\Entity\Engines */ ?>
            <tr>
                <td align='center'><?=$engine->getCode();
                    if ($engine->getDescription() != null) echo " (" . $engine->getDescription() . ")"; ?></td>
                <td align='center'>
                    <? if ($engine->getPconStart() != null || $engine->getPconEnd() != null)
                        echo $engine->getPconStart() . " - " . $engine->getPconEnd(); ?>
                </td>
            </tr>
        <? endforeach; ?>
    </table>
</div>