modules:
  - DoctrineModule
  - DoctrineORMModule
  - AssetManager
  - TwbBundle
# Внешние модули

  - Application
  - Navigator
  - AuthDoctrine
  - Admin
# Мои иодули

module_listener_options:
  module_paths:
    - './module'
    - './vendor'
  config_glob_paths:
    - 'config/autoload/{,*.}{global,local}.php'

db:
  prefix: 'prefix_'