<?
$this->headTitle('Страницы');
?>
<div class="ibox">
    <div class="ibox-title">
        <h5>Статические страницы</h5>
        <div class="ibox-tools">
            <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> Создать новую страницу</a>
        </div>
    </div>
    <div class="ibox-content">
        <div class="project-list">
            <table class="table table-hover">
                <tbody>
                <? /* @var $page \Pages\Entity\Pages */ ?>
                <? foreach ($pages as $page): ?>
                    <tr>
                        <td>
                            <? if ($page->getActive()) {
                                $status = 'Активна';
                                $activeClass = 'label-primary';
                            } else {
                                $status = 'Не активна';
                                $activeClass = 'label-danger';
                            }
                            ?>
                            <span class="label <?=$activeClass?>"><?=$status?></span>
                        </td>
                        <td class="project-title">
                            <h4><?=$page->getName(); ?></h4>
                            <small>Создана <?=date_format($page->getDate(), 'd.m.Y  H:i:s'); ?></small>
                        </td>
                        <td>
                            <b>Адрес страницы:</b><br>
                            <small>/page/<?=$page->getAlias(); ?></small>
                        </td>
                        <td class="project-content-preview">
                            <small><?=(mb_strlen($page->getContent()) > 432) ? mb_substr(strip_tags($page->getContent()), 0, 432) . '.....' : strip_tags($page->getContent()); ?></small>
                        </td>
                        <td class="project-actions">
                            <a href="<?=$this->url('admin/default', ['controller' => 'pages', 'action' => 'pagepreview', 'id' => $page->getPageId()])?>" class="btn btn-white btn-sm"><i class="fa fa-eye"></i> Просмотр</a>
                            <a href="<?=$this->url('admin/default', ['controller' => 'pages', 'action' => 'editpage', 'id' => $page->getPageId()])?>" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> Редактирование</a>
                        </td>
                    </tr>
                <? endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>