<? $homepage = ($this->basePath('/') == $_SERVER['REQUEST_URI']); ?>

<?=$this->doctype(); ?>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <?=$this->headTitle($this->getSiteParam('main_title'))->setSeparator(' | ')->setAutoEscape(false) ?>

    <?=$this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('img/favicon.png')))
        ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('css/font-awesome.min.css'))
        ->appendStylesheet($this->basePath('css/style.css'))
    ?>

    <!--[if lt IE 9]>
    <script src="<?=$this->basePath('js/html5shiv.js'); ?>"></script>
    <script src="<?=$this->basePath('js/respond.min.js'); ?>"></script>
    <![endif]-->

    <script>
        paceOptions = {
            elements: true
        };
    </script>
    <script src="<?=$this->basePath('js/pace.min.js'); ?>"></script>
</head>
<body>
<div id="wrapper">
    <div id="header" class="header">
        <nav class="navbar navbar-site navbar-default navbar-fixed-top">
            <div class="container">
                <div class="row contacts">
                    <div class="col-sm-3 col-sm-offset-6">
                        <a class="pull-right" href="tel:+000000000">Телефон: (000) 000-0000</a>
                    </div>
                    <div class="col-sm-3">
                        <a class="pull-right" href="mailto:ims.ltd.comp@gmail.com">Email: ims.ltd.comp@gmail.com</a>
                    </div>
                </div>
                <div class="row">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="<?=$this->url('home');?>" class="navbar-brand">
                            <i class="fa fa-fort-awesome"></i> <span>ООО</span> "ИМС"
                        </a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <?=$this->navigation('navigation')->menu()->setPartial('partial/main-navigation.phtml')->setUlClass('nav navbar-nav navbar-right'); ?>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <? if ($homepage): ?>
        <div id="intro" class="intro">
            <div class="container">
                <div id="slider1_container" class="slider-container">
                    <div u="loading" class="slider-loading"><div></div><div></div></div>

                    <!-- Slides Container -->
                    <div u="slides" class="slides-content">
                        <div>
                            <img u="image" src="img/slider/home/01.jpg" />
                            <div data-u="caption" data-t="0" class="slides-text-area">
                                <div data-u="caption" data-t="1" class="slides-text slides-text-tl">Touch swipe and responsive javascript image slider</div>
                                <div data-u="caption" data-t="2" class="slides-text slides-text-br">slideshow and responsive slider ...</div>
                            </div>
                        </div>
                        <div>
                            <img u="image" src="img/slider/home/02.jpg"/>
                        </div>
                        <div>
                            <img u="image" src="img/slider/home/03.jpg"/>
                        </div>
                        <div>
                            <img u="image" src="img/slider/home/04.jpg"/>
                        </div>
                    </div>

                    <div u="navigator" class="jssorb05">
                        <div u="prototype"></div>
                    </div>

                    <span u="arrowleft" class="jssora11l"></span>
                    <span u="arrowright" class="jssora11r"></span>
                </div>
            </div>
        </div>
    <? endif; ?>

    <div class="main-container">
        <div class="container">
            <? if (!$homepage): ?>
                <div class="no-intro"></div>
            <? endif; ?>
            <?=$this->content; ?>
        </div>
    </div>

    <? if ($homepage): ?>
        <div class="page-bottom-info">
            <div class="page-bottom-info-inner">
                <div class="page-bottom-info-content text-center">
                    <h1>Если у вас есть какие-либо вопросы, пожалуйста, позвоните нам (000) 555-5555</h1>
                    <a class="btn  btn-lg btn-primary-dark" href="tel:+000000000">
                        <i class="icon-mobile"></i> <span class="hide-xs color50">Позвонить сейчас:</span> (000) 555-5555 </a>
                </div>
            </div>
        </div>
    <? endif; ?>
    <div class="footer" id="footer">
        <div class="container">
            <?=$this->navigation('navigation')->menu()->setPartial('partial/main-navigation.phtml')->setUlClass('nav navbar-nav'); ?>
            <ul class="nav navbar-nav navbar-right">
                <li><div class="copyright">© 2015 ООО "ИМС"</div></li>
            </ul>
            <!--</nav>-->
        </div>
    </div>

</div>
<?=$this->inlineScript() ?>

<?=$this->headScript()
//        ->prependFile($this->basePath('js/machining.js'))
    ->prependFile($this->basePath('js/script.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
?>
</body>
</html>