<div class="row">
    <div class="col-sm-12">
        <div class="blog-post-wrapper">
            <article class="blog-post-item">
                <div class="inner-box">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="blog-post-header">
                                <h2>Наши контакты</h2>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="blog-post-content">
                            <div class="ymap">
                                <script type="text/javascript" charset="utf-8" src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=82GL0IBP7THkcHZVw_sfQuIqZkX7auq-&lang=ru_RU&sourceType=constructor"></script>
                            </div>
                            <div class="contacts">
                                <div class="title">Адрес:</div>г. Сарапул, ул. Труда, д. 49 (перекресток ул. Труда и ул. Пугачева)
                            </div>
                            <div class="contacts">
                                <div class="title">Email:</div><a href="mailto:ims.ltd.comp@gmail.com">ims.ltd.comp@gmail.com</a>
                            </div>
                            <div class="contacts">
                                <div class="title">Телефон:</div><a href="tel:+000000000">(000) 000-0000</a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="blog-post-bottom">
                                <div class="blog-post-time">05.01.2016</div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </div>
</div>