<? $this->headTitle('Механообработка');  ?>

<? $this->headLink()->appendStylesheet($this->basePath('css/glisse.css')); ?>

<? $this->headScript()->appendFile($this->basePath('js/glisse.js')); ?>
<? $this->headScript()->appendFile($this->basePath('js/plastic.js')); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="blog-post-wrapper">
            <article class="blog-post-item">
                <div class="inner-box">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="blog-post-header">
                                <h2>Литье пластмасс под давлением</h2>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="blog-post-content">
                            <p><b>Литье пластмасс под давлением</b> - это процесс переработки (преобразования)
                                пластмасс из исходного состояния в виде гранул в жидкое под воздействием температуры
                                и последующий впрыск расплавленной пластмассы в пресс-форму.</p>
                            <p>Используя метод "литье пластмасс под давлением" в мире в настоящее время производится до трети единичных пластмассовых изделий.</p>
                            <p>Для литья пластмасс используем практически любой материал по выбору заказчика.</p><br>
                            <h4>Почему Вам нужно мелкосерийное литье пластмасс</h4>
                            <p>Десять причин для выбора метода "литье пластмасс под давлением":</p>
                            <ol style="list-style-type: decimal; margin-left: 30px;">
                                <li>Любой цвет. Цвет может быть на полупрозрачной основе.</li>
                                <li>Поверхность. Высокий блеск и устойчивость против царапин.</li>
                                <li>Морозостойкость до -57 градусов Цельсия.</li>
                                <li>Возможность применения в пищевых и медицинских отраслях.</li>
                                <li>Высокие ударопрочность и жесткость.</li>
                                <li>Высокая эластичность.</li>
                                <li>Устойчивость к побелению под нагрузкой, деформации.</li>
                                <li>Стойкость к воздействию химических веществ и УФ-излучения.</li>
                                <li>Хорошие органолептические свойства, обеспечение герметичности.</li>
                                <li>Красивый внешний вид.</li>
                            </ol><br>
                            <h4>Какие детали мы отливаем</h4>
                            <p>Мы изготавливаем изделия методом <b>мелкосерийного литья пластмасс под давлением.</b>
                                Все сделаем сами, достаточно эскиза или фотографии изделия для начала разговора.</p>
                            <p>Можно изготавливать из пластмассы практически любые не очень крупные изделия: в первую очередь,
                                всевозможные корпуса, крышки и колпачки с резьбой и без; гайки и болты; кубики и фишки;
                                мягкие ручки; посуду; игрушки и канцтовары; товары для спорта и досуга,
                                <i>оригинальные корпуса для флеш накопителей (флешек);</i> прочие бытовые товары. </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="blog-post-bottom">
                                <div class="blog-post-time">05.01.2016</div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="blog-post-wrapper">
            <article class="blog-post-item">
                <div class="inner-box">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="blog-post-header">
                                <h2>Галлерея</h2>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="blog-post-content">
                            <div class="wrap-gallery">
                                <div class="gallery-border"></div>
                                <div class="gallery-container">
                                    <div class="gallery">
                                        <div class="gallery-item">
                                            <img src="<?=$this->basePath('img/photo/plastic/300/photo-1.jpg');?>"
                                                 class="galleryImage" rel="machining"
                                                 data-glisse-big="<?=$this->basePath('img/photo/plastic/1100/photo-1.jpg');?>">
                                        </div>
                                        <div class="gallery-item">
                                            <img src="<?=$this->basePath('img/photo/plastic/300/photo-2.jpg');?>"
                                                 class="galleryImage" rel="machining"
                                                 data-glisse-big="<?=$this->basePath('img/photo/plastic/1100/photo-2.jpg');?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="preloader"><i class="fa fa-cog fa-spin"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="blog-post-bottom">
                                <div class="blog-post-time">05.01.2016</div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </div>
</div>
